// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCw3S7qWdx07Ao7sl75PkmBtcrQPT1U_uI',
    appId: '1:461962602120:web:f32fc97c9d92f64a0d613d',
    messagingSenderId: '461962602120',
    projectId: 'naturemedix-32764',
    authDomain: 'naturemedix-32764.firebaseapp.com',
    storageBucket: 'naturemedix-32764.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCICprD7Zx21ClFu5ys71tAP89QocXbFDI',
    appId: '1:461962602120:android:c3ab3369c06ccb4b0d613d',
    messagingSenderId: '461962602120',
    projectId: 'naturemedix-32764',
    storageBucket: 'naturemedix-32764.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAG6xevyCr5QymvFkhaHlLKhZiY_HtkloM',
    appId: '1:461962602120:ios:24552f6ffa4ca4af0d613d',
    messagingSenderId: '461962602120',
    projectId: 'naturemedix-32764',
    storageBucket: 'naturemedix-32764.firebasestorage.app',
    iosClientId: '461962602120-u21alpljldgh0c26n015l7vglshe04ar.apps.googleusercontent.com',
    iosBundleId: 'com.example.naturemedix',
  );
}
